[behave]
steps_dst = features/steps/**/*.py,features/api/steps/**/*.py,features/android/steps/**/*.py,features/web/steps/**/*.py
# Use progress format to hide feature file content
format = progress2
# Do not show skipped steps
show_skipped = false
# Do not show timings
show_timings = false
# Only show log messages, no feature output
# This can help reduce output verbosity
# outfiles= ./allure-results
# Show only errors and failures
quiet = false
verbose = false